# Generated by Django 4.2.8 on 2025-10-09 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_listing_bidder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bidder',
            new_name='bidders',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='starting_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('user', 'listing', 'amount')},
        ),
        migrations.RemoveField(
            model_name='bid',
            name='is_winning',
        ),
    ]
